openapi: "3.1.0"
info:
  title: "RecipeManager API"
  description: "RecipeManager API"
  version: "1.0.0"
servers:
- url: "https://RecipeManager"
paths:
  /json/kotlinx-serialization:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Map_String"
components:
  schemas:
    Map:
      type: "object"
      properties: {}
    Map_String:
      type: "string"