openapi: "3.1.0"
info:
  title: "RecipeManager API"
  description: "RecipeManager API"
  version: "1.0.0"
servers:
- url: "https://RecipeManager"
paths:
  /:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IngredientDTO"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                type: "object"
  /json/kotlinx-serialization:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Map_String"
components:
  schemas:
    IngredientDTO:
      type: "object"
      properties:
        name:
          type: "string"
        type:
          type: "string"
          enum:
          - "VEGETABLE"
          - "FRUIT"
          - "CHEESE"
          - "FISH"
          - "MEET"
          - "PASTA"
          - "SPICE"
          - "OIL"
          - "SAUCE"
          - "EGG"
          - "OTHER"
      required:
      - "name"
      - "type"
    Map:
      type: "object"
      properties: {}
    Map_String:
      type: "string"