name: cooknco

services:
  backend:
    container_name: cooknco-backend
    build:
      context: .
    volumes:
      - pictures:/img
      - logs:/var/log/cooknco
      - /secrets/cooknco/db.properties:/app/config/db.properties:ro
      - /secrets/cooknco/application.properties:/app/config/application.yaml:ro
    ports:
      - "8080:8080"
    networks:
      - database-network
      - frontend-network
      - auth-network
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/health
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: cooknco-frontend
    build:
      context: frontend
    ports:
      - "443:80"
    networks:
      - frontend-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  database:
    container_name: cooknco-database
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
    networks:
      - database-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    container_name: cooknco-redis
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - auth-network
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pictures: {}
  logs: {}
  postgres_data: {}
  redis_data: {}

networks:
  frontend-network: {}
  database-network:
    internal: true
  auth-network:
    internal: true