package shared.enums

enum class Sort {
    NONE,
    NAME_ASCENDING,
    NAME_DESCENDING,
    LIKES_ASCENDING,
    LIKES_DESCENDING,
    DATE_ASCENDING,
    DATE_DESCENDING,
    RANDOM,
    BEST_MATCH,
}