-- apply changes
create table ingredient_translation (
  id                            bigint generated by default as identity not null,
  ingredient_id                 bigint,
  locale                        integer not null,
  name                          varchar(255) not null,
  constraint ck_ingredient_translation_locale check ( locale in (0,1)),
  constraint uq_ingredient_translation_ingredient_id_locale unique (ingredient_id,locale),
  constraint pk_ingredient_translation primary key (id)
);

-- foreign keys and indices
create index ix_ingredient_translation_ingredient_id on ingredient_translation (ingredient_id);
alter table ingredient_translation add constraint fk_ingredient_translation_ingredient_id foreign key (ingredient_id) references ingredients (id) on delete restrict on update restrict;

