-- apply changes
create table recipe_notes (
  id                            bigint generated by default as identity not null,
  recipe_id                     bigint not null,
  user_id                       bigint not null,
  notes                         varchar(2048) not null,
  constraint pk_recipe_notes primary key (id)
);
-
-- apply alter tables
alter table ingredient_translation alter column name type varchar(255) using name::varchar(255);
alter table users alter column username type varchar(255) using username::varchar(255);
alter table users alter column mail_hash type varchar(255) using mail_hash::varchar(255);
alter table users alter column token type varchar(255) using token::varchar(255);
-- foreign keys and indices
create index ix_recipe_notes_recipe_id on recipe_notes (recipe_id);
alter table recipe_notes add constraint fk_recipe_notes_recipe_id foreign key (recipe_id) references recipes (id) on delete restrict on update restrict;

create index ix_recipe_notes_user_id on recipe_notes (user_id);
alter table recipe_notes add constraint fk_recipe_notes_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

