-- apply changes
create table followers (
  id                            bigint generated by default as identity not null,
  follower_id                   bigint,
  followed_id                   bigint,
  constraint pk_followers primary key (id)
);

create table users (
  id                            bigint generated by default as identity not null,
  locale                        integer not null,
  notifications_enabled         boolean default false not null,
  username                      varchar not null,
  encrypted_mail                varchar not null,
  constraint ck_users_locale check ( locale in (0,1)),
  constraint pk_users primary key (id)
);

-- foreign keys and indices
create index ix_followers_follower_id on followers (follower_id);
alter table followers add constraint fk_followers_follower_id foreign key (follower_id) references users (id) on delete restrict on update restrict;

create index ix_followers_followed_id on followers (followed_id);
alter table followers add constraint fk_followers_followed_id foreign key (followed_id) references users (id) on delete restrict on update restrict;

