/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./components/ActionButton.vue')['default']
    AdminOnly: typeof import('./components/AdminOnly.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChipRow: typeof import('./components/ChipRow.vue')['default']
    Cookbook: typeof import('./components/Cookbook.vue')['default']
    CookbooksGrid: typeof import('./components/CookbooksGrid.vue')['default']
    CookbooksList: typeof import('./components/CookbooksList.vue')['default']
    EditablePicture: typeof import('./components/EditablePicture.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    FollowerDisplay: typeof import('./components/FollowerDisplay.vue')['default']
    FollowersDisplay: typeof import('./components/FollowersDisplay.vue')['default']
    Ingredient: typeof import('./components/Ingredient.vue')['default']
    IngredientNutrionalData: typeof import('./components/IngredientNutrionalData.vue')['default']
    IngredientNutritionalData: typeof import('./components/IngredientNutritionalData.vue')['default']
    InteractiblePictoInfo: typeof import('./components/InteractiblePictoInfo.vue')['default']
    PictoInfo: typeof import('./components/PictoInfo.vue')['default']
    Recipe: typeof import('./components/Recipe.vue')['default']
    RecipeFilter: typeof import('./components/RecipeFilter.vue')['default']
    RecipesList: typeof import('./components/RecipesList.vue')['default']
    RecipesPopup: typeof import('./components/RecipesPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./components/User.vue')['default']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
    UserList: typeof import('./components/UserList.vue')['default']
    UsersGrid: typeof import('./components/UsersGrid.vue')['default']
  }
}
