/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    EditablePicture: typeof import('./components/EditablePicture.vue')['default']
    FileUpload: typeof import('./components/FileUpload.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Interactible: typeof import('./components/Interactible.vue')['default']
    InteractiblePictoInfo: typeof import('./components/InteractiblePictoInfo.vue')['default']
    PictoInfo: typeof import('./components/PictoInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
