/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/cookbook/edit': RouteRecordInfo<'/cookbook/edit', '/cookbook/edit', Record<never, never>, Record<never, never>>,
    '/cookbook/list': RouteRecordInfo<'/cookbook/list', '/cookbook/list', Record<never, never>, Record<never, never>>,
    '/cookbook/view': RouteRecordInfo<'/cookbook/view', '/cookbook/view', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/ingredient/list': RouteRecordInfo<'/ingredient/list', '/ingredient/list', Record<never, never>, Record<never, never>>,
    '/ingredient/view': RouteRecordInfo<'/ingredient/view', '/ingredient/view', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/logout': RouteRecordInfo<'/logout', '/logout', Record<never, never>, Record<never, never>>,
    '/maintenance': RouteRecordInfo<'/maintenance', '/maintenance', Record<never, never>, Record<never, never>>,
    '/password/reset/': RouteRecordInfo<'/password/reset/', '/password/reset', Record<never, never>, Record<never, never>>,
    '/password/reset/email': RouteRecordInfo<'/password/reset/email', '/password/reset/email', Record<never, never>, Record<never, never>>,
    '/password/reset/new': RouteRecordInfo<'/password/reset/new', '/password/reset/new', Record<never, never>, Record<never, never>>,
    '/password/reset/success': RouteRecordInfo<'/password/reset/success', '/password/reset/success', Record<never, never>, Record<never, never>>,
    '/password/update/': RouteRecordInfo<'/password/update/', '/password/update', Record<never, never>, Record<never, never>>,
    '/password/update/success': RouteRecordInfo<'/password/update/success', '/password/update/success', Record<never, never>, Record<never, never>>,
    '/recipe/edit': RouteRecordInfo<'/recipe/edit', '/recipe/edit', Record<never, never>, Record<never, never>>,
    '/recipe/list': RouteRecordInfo<'/recipe/list', '/recipe/list', Record<never, never>, Record<never, never>>,
    '/recipe/view': RouteRecordInfo<'/recipe/view', '/recipe/view', Record<never, never>, Record<never, never>>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/user/edit': RouteRecordInfo<'/user/edit', '/user/edit', Record<never, never>, Record<never, never>>,
    '/user/list': RouteRecordInfo<'/user/list', '/user/list', Record<never, never>, Record<never, never>>,
    '/user/settings': RouteRecordInfo<'/user/settings', '/user/settings', Record<never, never>, Record<never, never>>,
    '/user/verify': RouteRecordInfo<'/user/verify', '/user/verify', Record<never, never>, Record<never, never>>,
    '/user/view': RouteRecordInfo<'/user/view', '/user/view', Record<never, never>, Record<never, never>>,
    '/verification-email-sent': RouteRecordInfo<'/verification-email-sent', '/verification-email-sent', Record<never, never>, Record<never, never>>,
  }
}
