/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/cookbook/edit': RouteRecordInfo<'/cookbook/edit', '/cookbook/edit', Record<never, never>, Record<never, never>>,
    '/cookbook/list': RouteRecordInfo<'/cookbook/list', '/cookbook/list', Record<never, never>, Record<never, never>>,
    '/cookbook/view': RouteRecordInfo<'/cookbook/view', '/cookbook/view', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/ingredient/view': RouteRecordInfo<'/ingredient/view', '/ingredient/view', Record<never, never>, Record<never, never>>,
    '/ingredients': RouteRecordInfo<'/ingredients', '/ingredients', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/logout': RouteRecordInfo<'/logout', '/logout', Record<never, never>, Record<never, never>>,
    '/maintenance': RouteRecordInfo<'/maintenance', '/maintenance', Record<never, never>, Record<never, never>>,
    '/recipe/edit': RouteRecordInfo<'/recipe/edit', '/recipe/edit', Record<never, never>, Record<never, never>>,
    '/recipe/list': RouteRecordInfo<'/recipe/list', '/recipe/list', Record<never, never>, Record<never, never>>,
    '/recipe/view': RouteRecordInfo<'/recipe/view', '/recipe/view', Record<never, never>, Record<never, never>>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/user/edit': RouteRecordInfo<'/user/edit', '/user/edit', Record<never, never>, Record<never, never>>,
    '/user/verify': RouteRecordInfo<'/user/verify', '/user/verify', Record<never, never>, Record<never, never>>,
    '/user/view': RouteRecordInfo<'/user/view', '/user/view', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
