name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Extract project version
      id: version
      run: |
        VERSION=$(grep -E '^version\s*=' build.gradle.kts | sed 's/.*"\(.*\)".*/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Detected version: $VERSION"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Gradle build
      run: ./gradlew clean build --no-daemon

    - name: List subprojects
      run: ./gradlew projects

    - name: Build and push images
      run: |
        for project in $(find . -name Dockerfile -exec dirname {} \;); do
          project=$(basename $project)
          echo "Building Docker image for $project..."
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cooknco-$project:${{ env.VERSION }} $project
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cooknco-$project:${{ env.VERSION }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cooknco-$project:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/cooknco-$project:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cooknco-$project:latest
        done
